name: teamEventMind2

services:
  db:
    image: postgres:16
    container_name: teamEventMind2-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - teamEventMind2_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # odoo:
  #   image: odoo:18
  #   container_name: teamEventMind2-odoo
  #   depends_on:
  #     - db
  #   ports:
  #     - "8075:8069"
  #   environment:
  #     HOST: db
  #     USER: odoo
  #     PASSWORD: odoo
  #   volumes:
  #     - teamEventMind2_odoo_data:/var/lib/odoo
  #     - ./:/mnt/extra-addons/EventMind
  #   restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    container_name: teamEventMind2-backend
    ports:
      - "8075:8069"
    restart: unless-stopped

volumes:
  teamEventMind2_db_data:
  teamEventMind2_odoo_data:

networks:
  default:
    name: teamEventMind2_network
